---
name: Continuous Integration

on:
  push:

jobs:
  nix-flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v21

      - name: Ensure the build succeeds
        run: nix build

      - name: Run `nix flake check` to run formatters, linters, and tests
        run: nix flake check --print-build-logs
